package org.iskcon.kms.geo;

import java.util.List;

/**
 * Turning what somebody is typing into addresses they can pick from (2026-09-05).
 *
 * <p><strong>Why this exists.</strong> The delivery address used to be free text handed to a
 * geocoder afterwards and hoped for. When the geocoder missed — and it misses often on Bengaluru
 * apartment complexes — the failure was silent, late, and on a screen nobody was watching: no
 * coordinates, so no travel estimate, so no leave-by, and nobody told. Picking from suggestions
 * moves that failure to the one moment a person is present to fix it, which is while they type.
 *
 * <p><strong>Why it is a server-side port and not a browser widget.</strong> The usual way to do
 * this is Google's JavaScript library with a key in the page, which means a key that has to be
 * locked to a referrer and can still be lifted out of the bundle. Proxying it keeps the credential
 * where every other credential in this application lives, gives one place to cap the quota, and
 * costs a round trip nobody will notice — a temple types a delivery address a few times a week.
 *
 * <p>Implementations never raise. No suggestions is an ordinary answer: the address box stays a
 * plain text box, exactly as it was, and the plan still saves.
 */
public interface PlaceSuggestionProvider {

	/**
	 * One thing somebody might have meant.
	 *
	 * @param placeId Google's stable identifier, kept on the plan so the address survives a road
	 *                being renamed. It is also the one piece of a Maps response whose storage the
	 *                licence is unambiguous about.
	 * @param description the whole address as Google writes it — what goes in the box when picked.
	 * @param primary  the leading part, for a list where the full address is too long to scan.
	 * @param secondary the rest of it.
	 */
	record Suggestion(String placeId, String description, String primary, String secondary) {
	}

	/** Where a picked suggestion actually is, looked up once when it is chosen. */
	record Place(String placeId, String formattedAddress, GeocodingProvider.Coordinates at) {
	}

	/** Whether suggestions can be offered at all. False leaves the address box a plain one. */
	boolean configured();

	/**
	 * Addresses matching what has been typed so far, best first, or an empty list.
	 *
	 * @param sessionToken groups the keystrokes of one search with the lookup that ends it, so Google
	 *                     bills the session once rather than per character. Generated by the caller
	 *                     and thrown away when a suggestion is picked.
	 */
	List<Suggestion> suggest(String typed, String sessionToken);

	/** The coordinates and canonical address behind one suggestion, or empty if it cannot be had. */
	java.util.Optional<Place> resolve(String placeId, String sessionToken);
}
